import type { Component } from 'svelte';
import { templateIcons } from '$sailor/generated/icons';

/**
 * Resolve a Lucide icon component by its PascalCase name
 * (e.g. `"FileText"`, `"Settings"`, `"ShoppingCart"`). Returns `null`
 * when the name is missing or unknown; callers pick their own fallback.
 *
 * Only icons declared in templates (`icon: 'Name'`) end up in the bundle —
 * the registry is generated by `npx sailor db:update` from a scan of all
 * `globalDefinitions` / `collectionDefinitions` / `blockDefinitions`. So
 * adding a new icon to a template requires a regen, same as any other
 * template change.
 */
export function getLucideIcon(name: string | undefined | null): Component | null {
  if (!name) return null;
  return (templateIcons[name] as Component | undefined) ?? null;
}
