# GitHub Pages configuration
title: Sailor CMS
description: A Smooth Sailin' CMS for SvelteKit

# SEO and title configuration
title_separator: '|'
url: 'https://jonkristian.github.io'
baseurl: '/sailorcms'

# Use Just the Docs theme
remote_theme: just-the-docs/just-the-docs

# Enable dark mode toggle with custom purple color scheme
# Use our custom color scheme
color_scheme: dark

# Custom color scheme
aux_links_new_tab: true

# Search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Navigation
nav_sort: case_insensitive

# Let Just the Docs handle syntax highlighting with its defaults

# Footer
footer_content: 'Copyright &copy; 2024 Sailor CMS. Distributed under the <a href="https://github.com/jonkristian/sailor-cms/blob/master/LICENSE">MIT License</a>.'

# Just the Docs specific settings
aux_links:
  'GitHub Repository':
    - 'https://github.com/jonkristian/sailor-cms'

# Enable copy code button
enable_copy_code_button: true

# Plugins (preserving existing ones)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Include/exclude (preserving and extending existing)
include:
  - _pages
exclude:
  - node_modules
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - package*.json
  - '*.config.js'
  - '*.config.ts'
  - src/
  - static/
  - .svelte-kit/
  - build/
  - .env*
